### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by tomanagle** [Aron-HD/rest-api#4]
Hey Aron,

Not an issue but just wanted to say that this is awesome! So glad you followed the tutorial and build something from it.

**Comment by Aron-HD** [comment]
Cheers! Learned a lot from it, and certainly plan to add onto it and deploy.

**Comment by tomanagle** [comment]
Let me know if you need a hand with deployment. I am thinking of making a video about how to deploy with Docker, Caddy on a DigitalOcean server.

**Comment by Aron-HD** [comment]
> Let me know if you need a hand with deployment. I am thinking of making a video about how to deploy with Docker, Caddy on a DigitalOcean server.

Would love to deploy it! Also do you have some sort of community channel like Discord / Slack?
